### ISSUE TITLE
Failure with Raspbian 2014-06-20 image

### ISSUE THREAD

**Issue by crazyquark** [notro/fbtft-spindle#1]
Hello,

I've tried on multiple systems and multiple configurations(Ubuntu120.04, 10, 14.04, Linux Mint) but the furthest I could get is stage2 where image creation failes.

This is the only error I can see usually:
qemu-1.1.0+dfsg/nbd.c:nbd_trip():L837: requested operation past EOF--bad client?

**Comment by notro** [comment]
On Ubuntu, did you downgrade qemu to 1.0.1?
https://github.com/notro/fbtft-spindle/wiki

**Comment by crazyquark** [comment]
Hi,

Yes, of course. I ran the downgrade script.
I will also try without it.

Also, I tried to use the latest raspbian image from the raspberry pi foundation.

**Comment by notro** [comment]
I'm going to rebuild the FBTFT image, so I just ran the commands from the wiki and it looks OK.
I haven't run all steps, since I'm going to do some changes to the scripts.
I forgot to capture the output of ./setup, but here's the output of the rest: https://gist.github.com/notro/9a67c4026a873e16589d

I'm using Ubuntu 12.04

**Comment by crazyquark** [comment]
I think the issue is that I was using Ubuntu 64-bit. Building now a x86 virtual machine and will run again. I'll close this as soon I am done.

**Comment by crazyquark** [comment]
I ran all the steps from the wiki on this fresh Ubuntu x86 120.4 LTS virtual machine and now when I get to fbtft-stage0 it breaks. Here's the output:
https://gist.github.com/e92e67275dea6501fed9.git

**Comment by notro** [comment]
```
+ sudo qemu-nbd --nocache -v -c /dev/nbd0 fbtft-stage0.qed
NBD device /dev/nbd0 is now connected to fbtft-stage0.qed
+ sudo mount /dev/nbd0p1 boot
+ sudo mount /dev/nbd0p2 rootfs
+ sudo mv rootfs/etc/ld.so.preload rootfs/etc/ld.so.preload.disable
+ sudo rm rootfs/etc/profile.d/raspi-config.sh
+ cat rootfs/etc/rpi-issue
+ CUR_ISSUE=Raspberry Pi reference 2014-06-20 (armhf)
Generated using spindle, http://asbradbury.org/projects/spindle/, 8fe9fd4, stage4-lxde-edu.qed
+ sudo tee rootfs/etc/rpi-issue
+ cat
FBTFT image reference 2014-07-24
Raspberry Pi reference 2014-06-20 (armhf)
Generated using spindle, http://asbradbury.org/projects/spindle/, 8fe9fd4, stage4-lxde-edu.qed
+ sudo cp rootfs/etc/rpi-issue boot/issue.txt
+ sudo umount /dev/nbd0p1
umount: /home/chris/Desktop/fbtft-spindle/spindle/work/boot: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
+ WAS_TRAPPED=1
```

I haven't had this problem.
You can try and show open files with 'lsof' or 'fuser'. Insert the command before umount in the script.
