### ISSUE TITLE
fbtft keyboard

### ISSUE THREAD

**Issue by rolfee** [notro/fbtft-spindle#3]
using raspbian wheezy fbtft builtin 

after boot i have no keyboard access

**Comment by notro** [comment]
If you mean keyboard not working, is it registered?

```
$ lsusb
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.
Bus 001 Device 004: ID 046d:c313 Logitech, Inc. Internet 350 Keyboard
Bus 001 Device 005: ID 045e:0084 Microsoft Corp. Basic Optical Mouse
```

**Comment by rolfee** [comment]
sorry newbie error had not rpi updated firmware !!
can the output be sent to hdmi at the same time ??

**Comment by notro** [comment]
Each display has it own device /dev/fb0 and /dev/fb1, and can be used separately. Here's some info on having X windows on two displays: https://github.com/notro/fbtft-spindle/wiki/Appendix#x-windows-multiseat

fbcp can be used to duplicate fb0 onto fb1 if that's what you mean: https://github.com/notro/fbtft-spindle/wiki/FBTFT-image#fbcp---framebuffer-copy
